" Copyright (c) 2026 Dawid Kurek <hello@dawikur.dev>

call ChiropteraLN('NeoTreeNormal', 'Normal')
call ChiropteraLN('NeoTreeNormalNC', 'NormalNC')
call ChiropteraLN('NeoTreeSignColumn', 'SignColumn')
call ChiropteraLN('NeoTreeCursorLine', 'CursorLine')
call ChiropteraLN('NeoTreeEndOfBuffer', 'EndOfBuffer')
call ChiropteraLN('NeoTreeFloatBorder', 'FloatBorder')
call ChiropteraLN('NeoTreeFloatTitle', 'FloatTitle')
call ChiropteraHL('NeoTreeDirectoryIcon', g:chiroptera.fg.blue, g:chiroptera.none)
call ChiropteraHL('NeoTreeDirectoryName', g:chiroptera.fg.blue, g:chiroptera.none)
call ChiropteraHL('NeoTreeRootName', g:chiroptera.fg.mark, g:chiroptera.none, 'bold')
call ChiropteraHL('NeoTreeDimText', g:chiroptera.fg.note, g:chiroptera.none)
call ChiropteraHL('NeoTreeIndentMarker', g:chiroptera.fg.ignore, g:chiroptera.none)
call ChiropteraHL('NeoTreeGitAdded', g:chiroptera.fg.green, g:chiroptera.none)
call ChiropteraHL('NeoTreeGitModified', g:chiroptera.fg.yellow, g:chiroptera.none)
call ChiropteraHL('NeoTreeGitDeleted', g:chiroptera.fg.red, g:chiroptera.none)
call ChiropteraHL('NeoTreeGitConflict', g:chiroptera.fg.red, g:chiroptera.none, 'bold')
call ChiropteraHL('NeoTreeGitUntracked', g:chiroptera.fg.cyan, g:chiroptera.none)
call ChiropteraHL('NeoTreeGitIgnored', g:chiroptera.fg.note, g:chiroptera.none)
call ChiropteraHL('NeoTreeGitUnstaged', g:chiroptera.fg.yellow, g:chiroptera.none)
call ChiropteraHL('NeoTreeGitStaged', g:chiroptera.ui.green, g:chiroptera.none)
