" Copyright (c) 2026 Dawid Kurek <hello@dawikur.dev>

call ChiropteraLN('NoiceCmdline', 'MsgArea')
call ChiropteraLN('NoiceCmdlineIcon', 'DiagnosticSignInfo')
call ChiropteraLN('NoiceCmdlineIconSearch', 'DiagnosticSignWarn')
call ChiropteraLN('NoiceCmdlinePopup', 'NormalFloat')
call ChiropteraLN('NoiceCmdlinePopupBorder', 'FloatBorder')
call ChiropteraLN('NoiceCmdlinePopupBorderSearch', 'DiagnosticSignWarn')
call ChiropteraLN('NoiceCmdlinePopupTitle', 'FloatTitle')
call ChiropteraLN('NoicePopup', 'NormalFloat')
call ChiropteraLN('NoicePopupBorder', 'FloatBorder')
call ChiropteraLN('NoicePopupmenu', 'Pmenu')
call ChiropteraLN('NoicePopupmenuBorder', 'FloatBorder')
call ChiropteraLN('NoicePopupmenuMatch', 'Special')
call ChiropteraLN('NoicePopupmenuSelected', 'PmenuSel')
call ChiropteraLN('NoiceScrollbar', 'PmenuSbar')
call ChiropteraLN('NoiceScrollbarThumb', 'PmenuThumb')
call ChiropteraLN('NoiceSplit', 'NormalFloat')
call ChiropteraLN('NoiceSplitBorder', 'FloatBorder')
call ChiropteraLN('NoiceFormatLevelError', 'DiagnosticVirtualTextError')
call ChiropteraLN('NoiceFormatLevelInfo', 'DiagnosticVirtualTextInfo')
call ChiropteraLN('NoiceFormatLevelWarn', 'DiagnosticVirtualTextWarn')
call ChiropteraLN('NoiceFormatProgressDone', 'Search')
call ChiropteraLN('NoiceFormatProgressTodo', 'CursorLine')
call ChiropteraLN('NoiceVirtualText', 'DiagnosticVirtualTextInfo')
