" Copyright (c) 2026 Dawid Kurek <hello@dawikur.dev>

call ChiropteraLN('RenderMarkdownH1', '@markup.heading.1')
call ChiropteraLN('RenderMarkdownH2', '@markup.heading.2')
call ChiropteraLN('RenderMarkdownH3', '@markup.heading.3')
call ChiropteraLN('RenderMarkdownH4', '@markup.heading.4')
call ChiropteraLN('RenderMarkdownH5', '@markup.heading.5')
call ChiropteraLN('RenderMarkdownH6', '@markup.heading.6')
call ChiropteraLN('RenderMarkdownH1Bg', 'DiffText')
call ChiropteraLN('RenderMarkdownH2Bg', 'DiffAdd')
call ChiropteraLN('RenderMarkdownH3Bg', 'DiffChange')
call ChiropteraLN('RenderMarkdownH4Bg', 'DiffDelete')
call ChiropteraLN('RenderMarkdownH5Bg', 'Visual')
call ChiropteraLN('RenderMarkdownH6Bg', 'CursorColumn')
call ChiropteraLN('RenderMarkdownCode', 'ColorColumn')
call ChiropteraLN('RenderMarkdownCodeBorder', 'ColorColumn')
call ChiropteraHL('RenderMarkdownCodeInfo', g:chiroptera.fg.note, g:chiroptera.ui, 'italic')
call ChiropteraHL('RenderMarkdownQuote', g:chiroptera.fg.note, g:chiroptera.none, 'italic')
call ChiropteraHL('RenderMarkdownBullet', g:chiroptera.fg.cyan, g:chiroptera.none)
call ChiropteraLN('RenderMarkdownDash', 'LineNr')
call ChiropteraLN('RenderMarkdownSign', 'SignColumn')
call ChiropteraHL('RenderMarkdownLink', g:chiroptera.fg.blue, g:chiroptera.none, 'underline')
call ChiropteraLN('RenderMarkdownChecked', '@markup.list.checked')
call ChiropteraLN('RenderMarkdownUnchecked', '@markup.list.unchecked')
call ChiropteraLN('RenderMarkdownSuccess', 'DiagnosticOk')
call ChiropteraLN('RenderMarkdownInfo', 'DiagnosticInfo')
call ChiropteraLN('RenderMarkdownHint', 'DiagnosticHint')
call ChiropteraLN('RenderMarkdownWarn', 'DiagnosticWarn')
call ChiropteraLN('RenderMarkdownError', 'DiagnosticError')
