" Copyright (c) 2026 Dawid Kurek <hello@dawikur.dev>

if has('nvim')
	call ChiropteraLN('@comment'             , 'Comment')
	call ChiropteraLN('@comment.documentation', 'Comment')
	call ChiropteraHL('@comment.error'       , g:chiroptera.raw.red_bright     , g:chiroptera.raw.none      )
	call ChiropteraHL('@comment.warning'     , g:chiroptera.raw.yellow_bright  , g:chiroptera.raw.none      )
	call ChiropteraHL('@comment.note'        , g:chiroptera.raw.cyan_bright    , g:chiroptera.raw.none      )
	call ChiropteraLN('@comment.todo'        , 'Todo')
	call ChiropteraLN('@constant'            , 'Constant')
	call ChiropteraHL('@constant.builtin'    , g:chiroptera.raw.cyan_bright    , g:chiroptera.raw.none      )
	call ChiropteraHL('@constant.macro'      , g:chiroptera.raw.cyan_bright    , g:chiroptera.raw.none      )
	call ChiropteraLN('@boolean'             , 'Boolean')
	call ChiropteraLN('@character'           , 'Character')
	call ChiropteraHL('@character.special'   , g:chiroptera.raw.yellow_bright  , g:chiroptera.raw.none      )
	call ChiropteraLN('@function'            , 'Function')
	call ChiropteraHL('@function.builtin'    , g:chiroptera.raw.cyan_bright    , g:chiroptera.raw.none      )
	call ChiropteraHL('@function.call'       , g:chiroptera.raw.magenta_bright , g:chiroptera.raw.none      )
	call ChiropteraHL('@function.method'     , g:chiroptera.raw.magenta_bright , g:chiroptera.raw.none      )
	call ChiropteraHL('@function.method.call', g:chiroptera.raw.magenta_bright , g:chiroptera.raw.none      )
	call ChiropteraHL('@function.macro'      , g:chiroptera.raw.cyan_bright    , g:chiroptera.raw.none      )
	call ChiropteraHL('@function.special'    , g:chiroptera.raw.cyan_bright    , g:chiroptera.raw.none      )
	call ChiropteraHL('@constructor'         , g:chiroptera.raw.blue           , g:chiroptera.raw.none      )
	call ChiropteraLN('@keyword'             , 'Keyword')
	call ChiropteraHL('@keyword.coroutine'   , g:chiroptera.raw.red            , g:chiroptera.raw.none      )
	call ChiropteraHL('@keyword.debug'       , g:chiroptera.raw.red_bright     , g:chiroptera.raw.none      )
	call ChiropteraHL('@keyword.directive'   , g:chiroptera.raw.magenta        , g:chiroptera.raw.none      )
	call ChiropteraHL('@keyword.directive.define', g:chiroptera.raw.magenta    , g:chiroptera.raw.none      )
	call ChiropteraHL('@keyword.modifier'    , g:chiroptera.raw.red            , g:chiroptera.raw.none      )
	call ChiropteraHL('@keyword.return'      , g:chiroptera.raw.red            , g:chiroptera.raw.none      )
	call ChiropteraHL('@keyword.conditional' , g:chiroptera.raw.red            , g:chiroptera.raw.none      )
	call ChiropteraHL('@keyword.repeat'      , g:chiroptera.raw.red            , g:chiroptera.raw.none      )
	call ChiropteraHL('@keyword.exception'   , g:chiroptera.raw.red_bright     , g:chiroptera.raw.none      )
	call ChiropteraHL('@keyword.function'    , g:chiroptera.raw.yellow         , g:chiroptera.raw.none      )
	call ChiropteraHL('@keyword.import'      , g:chiroptera.raw.magenta        , g:chiroptera.raw.none      )
	call ChiropteraHL('@keyword.operator'    , g:chiroptera.raw.magenta        , g:chiroptera.raw.none      )
	call ChiropteraHL('@keyword.type'        , g:chiroptera.raw.blue           , g:chiroptera.raw.none      )
	call ChiropteraLN('@number'              , 'Number')
	call ChiropteraLN('@number.float'        , 'Number')
	call ChiropteraLN('@operator'            , 'Operator')
	call ChiropteraHL('@parameter'           , g:chiroptera.raw.fg_bright      , g:chiroptera.raw.none      )
	call ChiropteraHL('@property'            , g:chiroptera.raw.fg_bright      , g:chiroptera.raw.none      )
	call ChiropteraHL('@module'              , g:chiroptera.raw.cyan           , g:chiroptera.raw.none      )
	call ChiropteraHL('@attribute'           , g:chiroptera.raw.cyan_bright    , g:chiroptera.raw.none      )
	call ChiropteraHL('@punctuation.delimiter', g:chiroptera.raw.none          , g:chiroptera.raw.none      )
	call ChiropteraHL('@punctuation.bracket' , g:chiroptera.raw.fg_dim         , g:chiroptera.raw.none      )
	call ChiropteraLN('@string'              , 'String')
	call ChiropteraLN('@string.documentation', 'String')
	call ChiropteraHL('@string.escape'       , g:chiroptera.raw.yellow_bright  , g:chiroptera.raw.none      )
	call ChiropteraHL('@string.regexp'       , g:chiroptera.raw.cyan           , g:chiroptera.raw.none      )
	call ChiropteraHL('@string.special'      , g:chiroptera.raw.yellow_bright  , g:chiroptera.raw.none      )
	call ChiropteraHL('@string.special.path' , g:chiroptera.raw.cyan           , g:chiroptera.raw.none      )
	call ChiropteraHL('@string.special.symbol', g:chiroptera.raw.yellow_bright , g:chiroptera.raw.none      )
	call ChiropteraHL('@string.special.url'  , g:chiroptera.raw.cyan           , g:chiroptera.raw.none      , 'underline')
	call ChiropteraLN('@tag'                 , 'Tag')
	call ChiropteraHL('@tag.attribute'       , g:chiroptera.raw.cyan_bright    , g:chiroptera.raw.none      )
	call ChiropteraLN('@tag.builtin'         , 'Tag')
	call ChiropteraHL('@tag.delimiter'       , g:chiroptera.raw.fg_dim         , g:chiroptera.raw.none      )
	call ChiropteraLN('@type'                , 'Type')
	call ChiropteraLN('@type.builtin'        , 'Type')
	call ChiropteraHL('@type.definition'     , g:chiroptera.raw.cyan_bright    , g:chiroptera.raw.none      )
	call ChiropteraHL('@type.qualifier'      , g:chiroptera.raw.red            , g:chiroptera.raw.none      )
	call ChiropteraLN('@variable'            , 'Identifier')
	call ChiropteraHL('@variable.builtin'    , g:chiroptera.raw.cyan_bright    , g:chiroptera.raw.none      )
	call ChiropteraLN('@variable.member'     , '@variable')
	call ChiropteraLN('@variable.parameter'  , '@variable')
	call ChiropteraLN('@lsp.type.class'      , '@type')
	call ChiropteraLN('@lsp.type.decorator'  , '@attribute')
	call ChiropteraLN('@lsp.type.enum'       , '@type')
	call ChiropteraLN('@lsp.type.enumMember' , '@module')
	call ChiropteraLN('@lsp.type.event'      , '@module')
	call ChiropteraLN('@lsp.type.function'   , '@function')
	call ChiropteraLN('@lsp.type.interface'  , '@type')
	call ChiropteraLN('@lsp.type.macro'      , '@attribute')
	call ChiropteraLN('@lsp.type.method'     , '@function')
	call ChiropteraLN('@lsp.type.namespace'  , '@module')
	call ChiropteraLN('@lsp.type.parameter'  , '@variable')
	call ChiropteraLN('@lsp.type.property'   , '@variable')
	call ChiropteraLN('@lsp.type.struct'     , '@type')
	call ChiropteraLN('@lsp.type.typeParameter', '@type')
	call ChiropteraLN('@lsp.type.variable'   , '@variable')
	call ChiropteraHL('@lsp.mod.deprecated'  , g:chiroptera.raw.none           , g:chiroptera.raw.none      , 'strikethrough')
	call ChiropteraHL('@markup.heading'      , g:chiroptera.raw.cyan           , g:chiroptera.raw.none      , 'bold')
	call ChiropteraHL('@markup.heading.1'    , g:chiroptera.raw.red_bright     , g:chiroptera.raw.none      , 'bold')
	call ChiropteraHL('@markup.heading.2'    , g:chiroptera.raw.yellow_bright  , g:chiroptera.raw.none      , 'bold')
	call ChiropteraHL('@markup.heading.3'    , g:chiroptera.raw.green_bright   , g:chiroptera.raw.none      , 'bold')
	call ChiropteraHL('@markup.heading.4'    , g:chiroptera.raw.cyan_bright    , g:chiroptera.raw.none      , 'bold')
	call ChiropteraHL('@markup.heading.5'    , g:chiroptera.raw.blue_bright    , g:chiroptera.raw.none      , 'bold')
	call ChiropteraHL('@markup.heading.6'    , g:chiroptera.raw.magenta_bright , g:chiroptera.raw.none      , 'bold')
	call ChiropteraHL('@markup.strong'       , g:chiroptera.raw.none           , g:chiroptera.raw.none      , 'bold')
	call ChiropteraHL('@markup.italic'       , g:chiroptera.raw.none           , g:chiroptera.raw.none      , 'italic')
	call ChiropteraHL('@markup.link'         , g:chiroptera.raw.cyan           , g:chiroptera.raw.none      , 'underline')
	call ChiropteraHL('@markup.link.label'   , g:chiroptera.raw.cyan_bright    , g:chiroptera.raw.none      )
	call ChiropteraHL('@markup.link.url'     , g:chiroptera.raw.cyan           , g:chiroptera.raw.none      , 'underline')
	call ChiropteraHL('@markup.list'         , g:chiroptera.raw.yellow         , g:chiroptera.raw.none      )
	call ChiropteraHL('@markup.list.checked' , g:chiroptera.raw.green_bright   , g:chiroptera.raw.none      )
	call ChiropteraHL('@markup.list.unchecked', g:chiroptera.raw.fg_dim        , g:chiroptera.raw.none      )
	call ChiropteraHL('@markup.math'         , g:chiroptera.raw.blue           , g:chiroptera.raw.none      )
	call ChiropteraHL('@markup.quote'        , g:chiroptera.raw.fg_dim         , g:chiroptera.raw.none      , 'italic')
	call ChiropteraHL('@markup.raw'          , g:chiroptera.raw.green          , g:chiroptera.raw.none      )
	call ChiropteraLN('@markup.raw.block'    , '@markup.raw')
	call ChiropteraHL('@diff.plus'           , g:chiroptera.raw.green_bright   , g:chiroptera.raw.none      )
	call ChiropteraHL('@diff.minus'          , g:chiroptera.raw.red_bright     , g:chiroptera.raw.none      )
	call ChiropteraHL('@diff.delta'          , g:chiroptera.raw.yellow_bright  , g:chiroptera.raw.none      )
endif
